//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo5
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> BaoHanh { get; set; }
    
        public virtual LOAISP LOAISP { get; set; }
    }
}
