create table Item (barcode integer generated by default as identity (start with 1), name varchar(255), price decimal(7, 2), stock integer, primary key (barcode));
create table OrderLine (Itembarcode integer not null, Orderid integer not null, primary key (Itembarcode, Orderid));
create table "Order" (id integer not null, date date, totalPrice decimal(7, 2), primary key (id));
alter table OrderLine add constraint FK_OrderLine_8392 foreign key (Itembarcode) references Item;
alter table OrderLine add constraint FK_OrderLine_697 foreign key (Orderid) references "Order";
