//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo13
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU
    {
        public int MaVatTu { get; set; }
        public string TenVatTu { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public string MaNSX { get; set; }
    
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
